name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: run install
        run: |
          make install
        env:
          CI: true

      - name: run linter
        run: |
          make lint

      - name: run build
        run: |
          touch .env
          echo ROLLBAR_TOKEN =${{ secrets.ROLLBAR_TOKEN }} >> .env
          make build
